- n_samples: 244
  name: 7779773train_set_size=244
  path: /network/scratch/l/letournv/nanophoto/comparison/experiments/datascaling/7779773train_set_size=244/unet_fast/images/images.npy
- n_samples: 104
  name: 7779753train_set_size=104
  path: /network/scratch/l/letournv/nanophoto/comparison/experiments/datascaling/7779753train_set_size=104/unet_fast/images/images.npy
- n_samples: 164
  name: 7779761train_set_size=164
  path: /network/scratch/l/letournv/nanophoto/comparison/experiments/datascaling/7779761train_set_size=164/unet_fast/images/images.npy
- n_samples: 224
  name: 7779771train_set_size=224
  path: /network/scratch/l/letournv/nanophoto/comparison/experiments/datascaling/7779771train_set_size=224/unet_fast/images/images.npy
- n_samples: 124
  name: 7779754train_set_size=124
  path: /network/scratch/l/letournv/nanophoto/comparison/experiments/datascaling/7779754train_set_size=124/unet_fast/images/images.npy
- n_samples: 224
  name: 7779770train_set_size=224
  path: /network/scratch/l/letournv/nanophoto/comparison/experiments/datascaling/7779770train_set_size=224/unet_fast/images/images.npy
- n_samples: 264
  name: 7779776train_set_size=264
  path: /network/scratch/l/letournv/nanophoto/comparison/experiments/datascaling/7779776train_set_size=264/unet_fast/images/images.npy
- n_samples: 84
  name: 7779749train_set_size=84
  path: /network/scratch/l/letournv/nanophoto/comparison/experiments/datascaling/7779749train_set_size=84/unet_fast/images/images.npy
- n_samples: 44
  name: 7779742train_set_size=44
  path: /network/scratch/l/letournv/nanophoto/comparison/experiments/datascaling/7779742train_set_size=44/unet_fast/images/images.npy
- n_samples: 44
  name: 7779744train_set_size=44
  path: /network/scratch/l/letournv/nanophoto/comparison/experiments/datascaling/7779744train_set_size=44/unet_fast/images/images.npy
- n_samples: 164
  name: 7779762train_set_size=164
  path: /network/scratch/l/letournv/nanophoto/comparison/experiments/datascaling/7779762train_set_size=164/unet_fast/images/images.npy
- n_samples: 264
  name: 7779777train_set_size=264
  path: /network/scratch/l/letournv/nanophoto/comparison/experiments/datascaling/7779777train_set_size=264/unet_fast/images/images.npy
- n_samples: 144
  name: 7779758train_set_size=144
  path: /network/scratch/l/letournv/nanophoto/comparison/experiments/datascaling/7779758train_set_size=144/unet_fast/images/images.npy
- n_samples: 204
  name: 7779768train_set_size=204
  path: /network/scratch/l/letournv/nanophoto/comparison/experiments/datascaling/7779768train_set_size=204/unet_fast/images/images.npy
- n_samples: 184
  name: 7779765train_set_size=184
  path: /network/scratch/l/letournv/nanophoto/comparison/experiments/datascaling/7779765train_set_size=184/unet_fast/images/images.npy
- n_samples: 224
  name: 7779769train_set_size=224
  path: /network/scratch/l/letournv/nanophoto/comparison/experiments/datascaling/7779769train_set_size=224/unet_fast/images/images.npy
- n_samples: 44
  name: 7779743train_set_size=44
  path: /network/scratch/l/letournv/nanophoto/comparison/experiments/datascaling/7779743train_set_size=44/unet_fast/images/images.npy
- n_samples: 64
  name: 7779745train_set_size=64
  path: /network/scratch/l/letournv/nanophoto/comparison/experiments/datascaling/7779745train_set_size=64/unet_fast/images/images.npy
- n_samples: 284
  name: 7779780train_set_size=284
  path: /network/scratch/l/letournv/nanophoto/comparison/experiments/datascaling/7779780train_set_size=284/unet_fast/images/images.npy
- n_samples: 284
  name: 7779778train_set_size=284
  path: /network/scratch/l/letournv/nanophoto/comparison/experiments/datascaling/7779778train_set_size=284/unet_fast/images/images.npy
- n_samples: 204
  name: 7779766train_set_size=204
  path: /network/scratch/l/letournv/nanophoto/comparison/experiments/datascaling/7779766train_set_size=204/unet_fast/images/images.npy
- n_samples: 124
  name: 7779756train_set_size=124
  path: /network/scratch/l/letournv/nanophoto/comparison/experiments/datascaling/7779756train_set_size=124/unet_fast/images/images.npy
- n_samples: 184
  name: 7779764train_set_size=184
  path: /network/scratch/l/letournv/nanophoto/comparison/experiments/datascaling/7779764train_set_size=184/unet_fast/images/images.npy
- n_samples: 104
  name: 7779751train_set_size=104
  path: /network/scratch/l/letournv/nanophoto/comparison/experiments/datascaling/7779751train_set_size=104/unet_fast/images/images.npy
- n_samples: 164
  name: 7779760train_set_size=164
  path: /network/scratch/l/letournv/nanophoto/comparison/experiments/datascaling/7779760train_set_size=164/unet_fast/images/images.npy
- n_samples: 84
  name: 7779750train_set_size=84
  path: /network/scratch/l/letournv/nanophoto/comparison/experiments/datascaling/7779750train_set_size=84/unet_fast/images/images.npy
- n_samples: 204
  name: 7779767train_set_size=204
  path: /network/scratch/l/letournv/nanophoto/comparison/experiments/datascaling/7779767train_set_size=204/unet_fast/images/images.npy
- n_samples: 144
  name: 7779759train_set_size=144
  path: /network/scratch/l/letournv/nanophoto/comparison/experiments/datascaling/7779759train_set_size=144/unet_fast/images/images.npy
- n_samples: 124
  name: 7779755train_set_size=124
  path: /network/scratch/l/letournv/nanophoto/comparison/experiments/datascaling/7779755train_set_size=124/unet_fast/images/images.npy
- n_samples: 244
  name: 7779774train_set_size=244
  path: /network/scratch/l/letournv/nanophoto/comparison/experiments/datascaling/7779774train_set_size=244/unet_fast/images/images.npy
- n_samples: 64
  name: 7779746train_set_size=64
  path: /network/scratch/l/letournv/nanophoto/comparison/experiments/datascaling/7779746train_set_size=64/unet_fast/images/images.npy
- n_samples: 104
  name: 7779752train_set_size=104
  path: /network/scratch/l/letournv/nanophoto/comparison/experiments/datascaling/7779752train_set_size=104/unet_fast/images/images.npy
- n_samples: 284
  name: 7779779train_set_size=284
  path: /network/scratch/l/letournv/nanophoto/comparison/experiments/datascaling/7779779train_set_size=284/unet_fast/images/images.npy
- n_samples: 264
  name: 7779775train_set_size=264
  path: /network/scratch/l/letournv/nanophoto/comparison/experiments/datascaling/7779775train_set_size=264/unet_fast/images/images.npy
- n_samples: 184
  name: 7779763train_set_size=184
  path: /network/scratch/l/letournv/nanophoto/comparison/experiments/datascaling/7779763train_set_size=184/unet_fast/images/images.npy
- n_samples: 244
  name: 7779772train_set_size=244
  path: /network/scratch/l/letournv/nanophoto/comparison/experiments/datascaling/7779772train_set_size=244/unet_fast/images/images.npy
- n_samples: 144
  name: 7779757train_set_size=144
  path: /network/scratch/l/letournv/nanophoto/comparison/experiments/datascaling/7779757train_set_size=144/unet_fast/images/images.npy
- n_samples: 84
  name: 7779748train_set_size=84
  path: /network/scratch/l/letournv/nanophoto/comparison/experiments/datascaling/7779748train_set_size=84/unet_fast/images/images.npy
- n_samples: 64
  name: 7779747train_set_size=64
  path: /network/scratch/l/letournv/nanophoto/comparison/experiments/datascaling/7779747train_set_size=64/unet_fast/images/images.npy
